Repository imgix/vue, pull requests merged in 2022-12, with the labels that each got.

#474 chore(deps): update node-ipc to 9.2.6
  yarn.lock
Labels: dependencies

#475 chore: fix action title
  .github/workflows/add-pr-to-project.yml
Labels: documentation

#459 ci(node): support lts and current
  .circleci/config.yml
Labels: enhancement

#473 chore(deps): update js-core to v3.7.0
  package.json
Labels: dependencies

#476 docs(readme): remove fossa badge and update contributors
  README.md
Labels: documentation
